server:
  port: 8082

spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:mysql://mysql-db:3306/cart-service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://eureka-sv:8761/eureka/
