server:
  port: 8083

spring:
  application:
    name: sale-service
  datasource:
    url: jdbc:mysql://mysql-db:3306/sale-service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://eureka-sv:8761/eureka/
